#' Create Phenotype keyword search pattern 
#' 
#' This creates a regex search pattern to find all phenotypes containing the keywords 
#' entered by the user. The search expression is not case sensitive and 
#' uses an "or" operator, so the phenotype only needs to contain one of the keywords.
#' The function also removes any spaces. 
#' 
#' @param keywords phenotype related keywords separated by "," <string>
#' @returns  A regex pattern used to search for keywords <string>
#' @example 
#' process_search_terms("muscle, fatigue, heart")
#' @export
 process_search_terms <- function(keywords) {
  keywords <- strsplit(keywords, ",")[[1]]
  output = c()
  for (i in seq(1, length(keywords))){
    cur = keywords[i]
    while (substr(cur, 1,1) == " ") {
      cur = substr(cur, 2, nchar(cur))
    }
    while (substr(cur, nchar(cur), nchar(cur)) == " ") {
      cur = substr(cur, 1, nchar(cur)-1)
    }
    output = append(output, paste0("(?i)", cur))
  }
  output <- paste(output, collapse = "|")
  return(output)
}


#' Subset the RD EWCE results using phenotype keywords 
#' 
#' This finds all results related to phenotypes that contain the kewords entered 
#' into the \code{process_search_terms} function. It further subests by
#' fold change and q value thresholds. 
#' 
#' @param Terms the regex search pattern generated by \code{process_search_terms} <string>
#' @param q_threshod q value maximum threshold <numeric>
#' @param fold_threhold fold change minimum threshold <numberic>
#' @param min_sd_from_mean Z score threshold <numeric> - possibly remove?
#' 
#' @returns A data frame of subset of RD EWCE results.
#' @export 
keyword_search_df <- function(Terms, 
                              q_threshold = 0.05,
                              fold_threshold = 1,
                              min_sd_from_mean = 0) {

  # remove as charcater below ?
  Phenos <- as.character(unique(phenotype_to_genes$Phenotype[
    stringr::str_detect(phenotype_to_genes$Phenotype, pattern = Terms)
    ]))
  DF <- results[results$list %in% Phenos &
                             results$q <= q_threshold & 
                             results$fold_change >= fold_threshold &
                             results$sd_from_mean >= min_sd_from_mean, ]
  return(DF)
}


#' Plot bar chart of RD EWCE subest 
#' 
#' Should redo this figure. Possibly reuse a better one from the report
#' 
#' @param DF The RD EWCE results subset to be visualised <dataframe>
#' @param keywords the keyword string (used to create title)
#' 
#' @returns a bar chart <ggplot>
#' @export
plot_phenotype_counts <- function(DF, keywords) {
  plot <- ggplot(DF, aes(x = CellType, 
                         fill = fold_change)) + 
    geom_bar() +  
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 45, 
                                     vjust = 0.5, hjust = 1, 
                                     size = 10) ) + 
    labs(title = paste0("Enrichment counts associated with:"),
         subtitle = paste(keywords,collapse = ", "),
         x = "Cell type", 
         y = "Enrichment count",
         fill = "Fold change") +
    scale_y_continuous(breaks = scales::pretty_breaks(),
                       expand = expansion(mult = c(0, .1))) 
  return (plot)
  }
